# Generated by Django 5.1.6 on 2025-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_remove_chat_participants_chat_receiver_chat_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
